baseURL = 'https://dondeaprendoaws.com/'
locale = 'es'
disableKinds = ['taxonomy', 'term']
defaultContentLanguage = 'es'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = false
    [markup.goldmark.extensions]
      linkify = false
    [markup.goldmark.extensions.typographer]
      disable = true

[outputs]
  home = ['HTML']
